"""empty message

Revision ID: e46abd9194e2
Revises: f61912b39c68
Create Date: 2023-10-06 14:49:50.349251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46abd9194e2'
down_revision = 'f61912b39c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_email', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['_email'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('_email')

    # ### end Alembic commands ###
